version: "3.9"

services:
  app:
    build: .
    container_name: task-for-redis-app   # имя контейнера для Spring Boot
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  redis:
    image: redis:latest
    container_name: task-for-redis-db    # имя контейнера для Redis
    ports:
      - "6379:6379"
